name: "Scan Folder with Python Script"
description: "Runs a Python script using Poetry to scan a folder"
inputs:
  # Required Arguments
  package:
    description: "The package to scan"
    required: true
  mode:
    description: "What type of SBOM scan you plan to do (e.g. python-requirements, pipenv, npm, yarn)"
    required: true
    # Optional arguments
  github_comments:
    description: "GitHub mode, will attempt to post comments to GitHub"
    required: false
    default: "true" # Assume we want to post github comments every time
  url:
    description: "The URL to process"
    required: false
    default: "https://api.ossprey.com"
  dry_run:
    description: "Dry run mode, it won't make any POST requests"
    required: false
    default: "false"
  verbose:
    description: "Verbose mode"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
