name: CICD - Test Code

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test OSSPREY GH Action with Python
        uses: ./  # Reference your local action in the repo
        with:
          package: "test/python_simple_math"
          mode: "python-requirements"
          github_comments: false
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}

      - name: Test OSSPREY GH Action with NPM
        uses: ./  # Reference your local action in the repo
        with:
          package: "test/npm_simple_math"
          mode: "npm"
          dry_run: true
          github_comments: false
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}

      - name: Test OSSPREY GH Action with NPM
        uses: ./  # Reference your local action in the repo
        with:
          package: "test/yarn_simple_math"
          mode: "yarn"
          dry_run: true
          github_comments: false
          verbose: true
        env:
          API_KEY: ${{ secrets.OSSPREY_API_KEY }}