name: CICD - Test Code

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install poetry

      - name: Run Unit Tests
        run: |
          poetry install
          poetry run pytest

      - name: Test OSSPREY GH Action
        uses: ./scan  # Reference your local action in the repo
        with:
          folder: "test/example_package"
