name: Run OSSPREY Scanner

on:
  push:
    branches:
      - main

jobs:
  run-ossprey-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code to scan
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the OSSPREY scanner
      - name: Run OSSPREY Scanner
        uses: OSSPREY-Security/gh-action@main
        with:
          folder: "test/simple_math"
